/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminVisualEditorRouteImport } from './routes/_authenticated/admin/visual-editor'
import { Route as AuthenticatedAdminVariantsRouteImport } from './routes/_authenticated/admin/variants'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPageBuilderRouteImport } from './routes/_authenticated/admin/page-builder'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin/inventory'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminCmsRouteImport } from './routes/_authenticated/admin/cms'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin/brands'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin/products.index'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin/orders.index'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated/admin/customers.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin/blog.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin/products.$id'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated/admin/orders.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin/customers.$id'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin/blog.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVisualEditorRoute =
  AuthenticatedAdminVisualEditorRouteImport.update({
    id: '/visual-editor',
    path: '/visual-editor',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVariantsRoute =
  AuthenticatedAdminVariantsRouteImport.update({
    id: '/variants',
    path: '/variants',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPageBuilderRoute =
  AuthenticatedAdminPageBuilderRouteImport.update({
    id: '/page-builder',
    path: '/page-builder',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsRoute = AuthenticatedAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/blog/$id',
    path: '/blog/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/page-builder': typeof AuthenticatedAdminPageBuilderRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/variants': typeof AuthenticatedAdminVariantsRoute
  '/admin/visual-editor': typeof AuthenticatedAdminVisualEditorRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account': typeof AuthenticatedAccountRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/page-builder': typeof AuthenticatedAdminPageBuilderRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/variants': typeof AuthenticatedAdminVariantsRoute
  '/admin/visual-editor': typeof AuthenticatedAdminVisualEditorRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/page-builder': typeof AuthenticatedAdminPageBuilderRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/variants': typeof AuthenticatedAdminVariantsRoute
  '/_authenticated/admin/visual-editor': typeof AuthenticatedAdminVisualEditorRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/order-confirmation'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/wishlist'
    | '/admin'
    | '/account'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/analytics'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/coupons'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/page-builder'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/variants'
    | '/admin/visual-editor'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/blog/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/order-confirmation'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/wishlist'
    | '/account'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/analytics'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/coupons'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/page-builder'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/variants'
    | '/admin/visual-editor'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/blog'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/order-confirmation'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/track-order'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/cms'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/page-builder'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/variants'
    | '/_authenticated/admin/visual-editor'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/orders/$id'
    | '/_authenticated/admin/products/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/customers/'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/visual-editor': {
      id: '/_authenticated/admin/visual-editor'
      path: '/visual-editor'
      fullPath: '/admin/visual-editor'
      preLoaderRoute: typeof AuthenticatedAdminVisualEditorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/variants': {
      id: '/_authenticated/admin/variants'
      path: '/variants'
      fullPath: '/admin/variants'
      preLoaderRoute: typeof AuthenticatedAdminVariantsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/page-builder': {
      id: '/_authenticated/admin/page-builder'
      path: '/page-builder'
      fullPath: '/admin/page-builder'
      preLoaderRoute: typeof AuthenticatedAdminPageBuilderRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms': {
      id: '/_authenticated/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AuthenticatedAdminCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCmsRoute: typeof AuthenticatedAdminCmsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPageBuilderRoute: typeof AuthenticatedAdminPageBuilderRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminVariantsRoute: typeof AuthenticatedAdminVariantsRoute
  AuthenticatedAdminVisualEditorRoute: typeof AuthenticatedAdminVisualEditorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminCmsRoute: AuthenticatedAdminCmsRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminPageBuilderRoute: AuthenticatedAdminPageBuilderRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
    AuthenticatedAdminVariantsRoute: AuthenticatedAdminVariantsRoute,
    AuthenticatedAdminVisualEditorRoute: AuthenticatedAdminVisualEditorRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
    AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
    AuthenticatedAdminCustomersIndexRoute:
      AuthenticatedAdminCustomersIndexRoute,
    AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
